esphome:
  name: anemometre
  friendly_name: Anemometre

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "**********************************"

ota:
  - platform: esphome
    password: "**********************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wind-Speed Fallback Hotspot"
    password: "h4rFkJCqsvba"

captive_portal:

uart:
  tx_pin: 19
  rx_pin: 22
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
  - id: wind_speed_meter
    address: 1
    modbus_id: modbus1
    setup_priority: -10
    command_throttle: 200ms
    update_interval: 1s

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_speed_meter
    name: "Wind speed"
    device_class: wind_speed
    register_type: read
    address: 0
    unit_of_measurement: "m/s"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - max:
          window_size: 5
          send_every: 5
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12
